openapi: 3.0.0
info:
  title: Kaixin
  description: 开心 Open API。
  contact:
    name: Roy QIU
    email: karoyqiu@gmail.com
  version: "0.1"
servers:
- url: https://api-v3-test.hlwcr.cn
  description: 测试环境
security:
- Authorization: []
tags:
- name: Ecomm
  description: 电子商务
- name: Email
  description: 电子邮件
- name: Session
  description: 会话
- name: User
  description: 用户
paths:
  /session:
    post:
      tags:
      - Session
      summary: 登录
      description: 使用用户名和密码登录。
      operationId: SignIn
      parameters:
      - name: k
        in: query
        description: 应用的 APP KEY
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: t
        in: query
        description: 发送请求时的时间戳，UNIX 时间，毫秒，与 UTC 时间前后相差不得超过 15 分钟
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: z
        in: query
        description: 随机字符串，推荐 UUID，15 分钟内不得重复
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: uuid
      - name: s
        in: query
        description: 请求签名，算法详见 docs/SIGNATURE.md
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        description: 登录请求
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SignInRequest'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
              examples:
                成功:
                  $ref: '#/components/examples/session'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                用户名/密码错误:
                  value:
                    code: 1
                    msg: Invalid username and/or password.
      security: []
    delete:
      tags:
      - Session
      summary: 注销
      description: 注销已有登录，注销后访问令牌和更新令牌失效。
      operationId: SignOut
      parameters:
      - name: k
        in: query
        description: 应用的 APP KEY
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: t
        in: query
        description: 发送请求时的时间戳，UNIX 时间，毫秒，与 UTC 时间前后相差不得超过 15 分钟
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: z
        in: query
        description: 随机字符串，推荐 UUID，15 分钟内不得重复
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: uuid
      - name: s
        in: query
        description: 请求签名，算法详见 docs/SIGNATURE.md
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                成功:
                  value:
                    code: 0
                    msg: ""
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                无效访问令牌:
                  value:
                    code: 1
                    msg: Invalid access token.
                签名错误:
                  value:
                    code: 14
                    msg: Invalid signature.
    patch:
      tags:
      - Session
      summary: 更新令牌
      description: 使用更新令牌更新令牌。
      operationId: RefreshToken
      parameters:
      - name: k
        in: query
        description: 应用的 APP KEY
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: t
        in: query
        description: 发送请求时的时间戳，UNIX 时间，毫秒，与 UTC 时间前后相差不得超过 15 分钟
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: z
        in: query
        description: 随机字符串，推荐 UUID，15 分钟内不得重复
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: uuid
      - name: s
        in: query
        description: 请求签名，算法详见 docs/SIGNATURE.md
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        description: 更新令牌请求
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
              examples:
                成功:
                  $ref: '#/components/examples/session'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                无效访问令牌:
                  value:
                    code: 1
                    msg: Invalid access token.
                签名错误:
                  value:
                    code: 14
                    msg: Invalid signature.
  /user:
    post:
      tags:
      - User
      summary: 注册新用户
      description: 注册新用户。
      operationId: SignUp
      parameters:
      - name: k
        in: query
        description: 应用的 APP KEY
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: t
        in: query
        description: 发送请求时的时间戳，UNIX 时间，毫秒，与 UTC 时间前后相差不得超过 15 分钟
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: z
        in: query
        description: 随机字符串，推荐 UUID，15 分钟内不得重复
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: uuid
      - name: s
        in: query
        description: 请求签名，算法详见 docs/SIGNATURE.md
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        description: 注册信息。
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
            examples:
              示例:
                value:
                  username: karoyqiu
                  password: blablabla
                  email: karoyqiu@gmail.com
                  wechat: abcdefg
                  agent_code: "123456"
                  agent_signature: xxxxxxxxxxxxxx
        required: true
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                成功:
                  value:
                    code: 0
                    msg: ""
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                电子邮箱未验证或验证码错误:
                  value:
                    code: 1
                    msg: Email unverified or invalid vcode.
                无效代理:
                  value:
                    code: 2
                    msg: Invalid agent code.
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                无效访问令牌:
                  value:
                    code: 1
                    msg: Invalid access token.
                签名错误:
                  value:
                    code: 14
                    msg: Invalid signature.
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                用户名已注册:
                  value:
                    code: 1
                    msg: Username conflict.
                电子邮箱已注册:
                  value:
                    code: 2
                    msg: Email conflict.
      security: []
    patch:
      tags:
      - User
      summary: 修改当前用户密码
      description: 修改已登录用户密码。
      operationId: ChangePassword
      parameters:
      - name: k
        in: query
        description: 应用的 APP KEY
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: t
        in: query
        description: 发送请求时的时间戳，UNIX 时间，毫秒，与 UTC 时间前后相差不得超过 15 分钟
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: z
        in: query
        description: 随机字符串，推荐 UUID，15 分钟内不得重复
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: uuid
      - name: s
        in: query
        description: 请求签名，算法详见 docs/SIGNATURE.md
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        description: 新/旧密码。
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                成功:
                  value:
                    code: 0
                    msg: ""
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                原密码错误:
                  value:
                    code: 1
                    msg: Invalid original password.
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                无效访问令牌:
                  value:
                    code: 1
                    msg: Invalid access token.
                签名错误:
                  value:
                    code: 14
                    msg: Invalid signature.
  /user/{username}:
    patch:
      tags:
      - User
      summary: 内部 API，不对外开放
      description: 不验证原密码，直接设置新密码。
      operationId: SetPassword
      parameters:
      - name: k
        in: query
        description: 应用的 APP KEY
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: t
        in: query
        description: 发送请求时的时间戳，UNIX 时间，毫秒，与 UTC 时间前后相差不得超过 15 分钟
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: z
        in: query
        description: 随机字符串，推荐 UUID，15 分钟内不得重复
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: uuid
      - name: s
        in: query
        description: 请求签名，算法详见 docs/SIGNATURE.md
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: username
        in: path
        description: 要设置密码的用户名
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/body'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                成功:
                  value:
                    code: 0
                    msg: ""
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                无效访问令牌:
                  value:
                    code: 1
                    msg: Invalid access token.
                签名错误:
                  value:
                    code: 14
                    msg: Invalid signature.
      security: []
  /user/availability:
    get:
      tags:
      - Email
      - User
      summary: 获取用户名/email 是否可用
      description: 获取用户名/email 是否可用于注册新用户。
      operationId: IsUserAvailable
      parameters:
      - name: k
        in: query
        description: 应用的 APP KEY
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: t
        in: query
        description: 发送请求时的时间戳，UNIX 时间，毫秒，与 UTC 时间前后相差不得超过 15 分钟
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: z
        in: query
        description: 随机字符串，推荐 UUID，15 分钟内不得重复
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: uuid
      - name: s
        in: query
        description: 请求签名，算法详见 docs/SIGNATURE.md
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: filter
        in: query
        description: 希望用于注册的用户名/email，username 和 email 至少设置一个
        required: true
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/filter'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                用户名/email 可用:
                  value:
                    code: 0
                    msg: ""
                用户名/email 不可用:
                  value:
                    code: 1
                    msg: The username/email is unavailable.
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                无效访问令牌:
                  value:
                    code: 1
                    msg: Invalid access token.
                签名错误:
                  value:
                    code: 14
                    msg: Invalid signature.
      security: []
  /email/vcode:
    post:
      tags:
      - Email
      - User
      summary: 发送验证邮件
      description: 向指定邮箱发送包含验证码的邮件。
      operationId: SendVerificationEmail
      parameters:
      - name: k
        in: query
        description: 应用的 APP KEY
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: t
        in: query
        description: 发送请求时的时间戳，UNIX 时间，毫秒，与 UTC 时间前后相差不得超过 15 分钟
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: z
        in: query
        description: 随机字符串，推荐 UUID，15 分钟内不得重复
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: uuid
      - name: s
        in: query
        description: 请求签名，算法详见 docs/SIGNATURE.md
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SendVerificationEmailRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                成功:
                  value:
                    code: 0
                    msg: ""
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                无效访问令牌:
                  value:
                    code: 1
                    msg: Invalid access token.
                签名错误:
                  value:
                    code: 14
                    msg: Invalid signature.
        "429":
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                发送请求过多:
                  value:
                    code: 1
                    msg: You have sent too many verification emails.
      security: []
  /email/reset-password:
    post:
      tags:
      - Email
      - User
      summary: 发送重置密码邮件
      description: 向指定邮箱发送包含重置密码链接的邮件。
      operationId: SendResetPasswordEmail
      parameters:
      - name: k
        in: query
        description: 应用的 APP KEY
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: t
        in: query
        description: 发送请求时的时间戳，UNIX 时间，毫秒，与 UTC 时间前后相差不得超过 15 分钟
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: z
        in: query
        description: 随机字符串，推荐 UUID，15 分钟内不得重复
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: uuid
      - name: s
        in: query
        description: 请求签名，算法详见 docs/SIGNATURE.md
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SendResetPasswordEmailRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                成功:
                  value:
                    code: 0
                    msg: ""
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                无效访问令牌:
                  value:
                    code: 1
                    msg: Invalid access token.
                签名错误:
                  value:
                    code: 14
                    msg: Invalid signature.
        "429":
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                发送请求过多:
                  value:
                    code: 1
                    msg: You have sent too many reset password emails.
      security: []
  /ecomm/activation:
    post:
      tags:
      - Ecomm
      summary: 激活
      description: 使用序列号激活应用。
      operationId: Activate
      parameters:
      - name: k
        in: query
        description: 应用的 APP KEY
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: t
        in: query
        description: 发送请求时的时间戳，UNIX 时间，毫秒，与 UTC 时间前后相差不得超过 15 分钟
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: z
        in: query
        description: 随机字符串，推荐 UUID，15 分钟内不得重复
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: uuid
      - name: s
        in: query
        description: 请求签名，算法详见 docs/SIGNATURE.md
        required: true
        style: form
        explode: true
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ActivateRequest'
            encoding:
              sn:
                style: form
                explode: false
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                成功:
                  value:
                    code: 0
                    msg: ""
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivateResponse'
              examples:
                序列号无效:
                  value:
                    code: 1
                    msg: Some of the serial numbers are invalid.
                    data:
                    - code: 1
                      msg: No such serial number.
                      sn: sn-1
                    - code: 2
                      msg: The serial number is not for this application.
                      sn: sn-2
                    - code: 3
                      msg: The serial number is unavailable.
                      sn: sn-3
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                无效访问令牌:
                  value:
                    code: 1
                    msg: Invalid access token.
                签名错误:
                  value:
                    code: 14
                    msg: Invalid signature.
        "429":
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              examples:
                发送请求过多:
                  value:
                    code: 1
                    msg: You have sent too many reset password emails.
components:
  schemas:
    CommonResponse:
      title: 公共响应
      type: object
      properties:
        code:
          type: integer
          description: 错误代码，如果成功则为零
        msg:
          type: string
          description: 错误消息，如果成功则为空
      description: 公共响应结构，包含错误代码和消息。
    Session:
      title: 会话
      description: 会话对象。
      example:
        $ref: '#/components/examples/session'
      allOf:
      - $ref: '#/components/schemas/CommonResponse'
      - type: object
        properties:
          data:
            $ref: '#/components/schemas/Session_data'
    SignInRequest:
      title: 登录请求
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
          description: 用户名
        password:
          type: string
          description: 密码明文
          format: password
      description: 使用用户名和密码登录时的请求。
      example:
        username: karoyqiu
        password: blablabla
    RefreshTokenRequest:
      title: 更新令牌请求
      required:
      - refresh_token
      type: object
      properties:
        refresh_token:
          type: string
          description: 更新令牌
          format: byte
      description: 更新令牌时的请求。
      example:
        refresh_token: xxxxxxxxxxxxxxxxxxx
    SignUpRequest:
      title: 注册请求
      required:
      - email
      - password
      - username
      type: object
      properties:
        username:
          minLength: 6
          pattern: '[a-z0-9]{6,}'
          type: string
          description: 用户名
        password:
          minLength: 6
          type: string
          description: 密码明文
          format: password
        email:
          type: string
          description: 电子邮箱
          format: email
        phone:
          type: string
          description: 手机号码
        wechat:
          type: string
          description: 微信号
        line:
          type: string
          description: Line
        whatsapp:
          type: string
          description: WhatsApp
        agent_code:
          type: string
          description: 代理编码
      description: 注册用户所需要的信息。
    ChangePasswordRequest:
      title: 修改密码请求
      required:
      - new
      - original
      type: object
      properties:
        original:
          type: string
          description: 原密码明文
          format: password
        new:
          minLength: 6
          type: string
          description: 新密码明文
          format: password
      description: 提供新/旧密码。
    SendVerificationEmailRequest:
      title: 发送验证邮件请求
      required:
      - to
      type: object
      properties:
        to:
          type: string
          description: 要发送验证邮件的邮箱
          format: email
      description: 请求向指定邮箱发送验证邮件。
    SendResetPasswordEmailRequest:
      title: 发送重置密码邮件请求
      description: 请求向指定邮箱发送验证邮件。
      allOf:
      - $ref: '#/components/schemas/SendVerificationEmailRequest'
      - required:
        - link
        type: object
        properties:
          link:
            type: string
            description: 一次性重置密码链接
            format: uri
    ActivateRequest:
      title: 激活请求
      required:
      - sn
      type: object
      properties:
        sn:
          type: array
          description: 要使用的序列号列表
          items:
            type: string
      description: 使用指定序列号激活应用。
    ActivateResponse:
      title: 激活响应
      description: 如果在激活过程中有序列号不能使用，则在此响应中返回。
      allOf:
      - $ref: '#/components/schemas/CommonResponse'
      - type: object
        properties:
          data:
            type: array
            description: 序列号问题列表
            items:
              allOf:
              - $ref: '#/components/schemas/CommonResponse'
              - type: object
                properties:
                  sn:
                    type: string
                    description: 有问题的序列号
    body:
      required:
      - password
      type: object
      properties:
        password:
          type: string
          description: 新密码
          format: password
    filter:
      minProperties: 1
      type: object
      properties:
        username:
          type: string
          description: 用户名
        email:
          type: string
          description: Email
          format: email
      additionalProperties: false
    Session_data:
      type: object
      properties:
        access_token:
          type: string
          description: 访问令牌
        expires_in:
          type: integer
          description: 访问令牌有效期长度，秒
        refresh_token:
          type: string
          description: 更新令牌
        refresh_token_expires_in:
          type: integer
          description: 更新令牌有效期长度，秒
        id_token:
          type: string
          description: ID Token，JWT 格式
  responses:
    success:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CommonResponse'
          examples:
            成功:
              value:
                code: 0
                msg: ""
    unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CommonResponse'
          examples:
            无效访问令牌:
              value:
                code: 1
                msg: Invalid access token.
            签名错误:
              value:
                code: 14
                msg: Invalid signature.
  parameters:
    app-key:
      name: k
      in: query
      description: 应用的 APP KEY
      required: true
      style: form
      explode: true
      schema:
        type: string
    timestamp:
      name: t
      in: query
      description: 发送请求时的时间戳，UNIX 时间，毫秒，与 UTC 时间前后相差不得超过 15 分钟
      required: true
      style: form
      explode: true
      schema:
        type: integer
        format: int64
    nonce:
      name: z
      in: query
      description: 随机字符串，推荐 UUID，15 分钟内不得重复
      required: true
      style: form
      explode: true
      schema:
        type: string
        format: uuid
    signature:
      name: s
      in: query
      description: 请求签名，算法详见 docs/SIGNATURE.md
      required: true
      style: form
      explode: true
      schema:
        type: string
  examples:
    invalid-refresh-token:
      value:
        code: 2
        msg: Invalid refresh token.
    session:
      value:
        code: 0
        msg: ""
        data:
          access_token: xxxxxxxxxxxxxxxxxxx
          expires_in: 3600
          refresh_token: xxxxxxxxxxxxxxxxxxx
          refresh_token_expires_in: 2592000
          id_token: xxxxxxxxxxxxxxxxxxx
  securitySchemes:
    Authorization:
      type: http
      description: 登录成功后的 ID Token
      scheme: bearer
      bearerFormat: JWT
